name: deployment

on:
  release:
    types:
      - created

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install pypa/build
        run: python -m pip install --upgrade pip build

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir=dist/ .

      - name: Publish distribution 📦
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
